import { createKeyPairSignerFromBytes } from 'gill';
import { readFileSync, existsSync } from 'fs';
import { join, resolve } from 'path';

/**
 * Load test keypairs from keypairs folder (generated by generate_keypair.sh)
 * 
 * Loads all keypairs from keypairs/ folder in project root:
 * - Authority, Node Owner
 * - All Public Nodes (from keypairs.json)
 * - All Confidential Nodes (from keypairs.json)
 * 
 * Usage:
 *   import { loadTestKeypairs } from './load-test-keypairs.js';
 *   const keypairs = await loadTestKeypairs();
 */

// Path to keypairs folder in project root (assuming clients/sdk is in clients/sdk)
const KEYPAIRS_DIR = resolve(process.cwd(), '../../keypairs');
const KEYPAIRS_JSON_PATH = join(KEYPAIRS_DIR, 'keypairs.json');

export interface TestKeypairs {
  authority: Awaited<ReturnType<typeof createKeyPairSignerFromBytes>>;
  nodeOwner: Awaited<ReturnType<typeof createKeyPairSignerFromBytes>>;
  publicNodes: Awaited<ReturnType<typeof createKeyPairSignerFromBytes>>[];
  confidentialNodes: Awaited<ReturnType<typeof createKeyPairSignerFromBytes>>[];
}

interface KeypairsJson {
  public_nodes: Array<{ pubkey: string; keypair_path: string }>;
  confidential_nodes: Array<{ pubkey: string; keypair_path: string }>;
  authority: { pubkey: string; keypair_path: string };
  node_owner: { pubkey: string; keypair_path: string };
}

export async function loadTestKeypairs(): Promise<TestKeypairs> {
  function loadKeypairFromFile(filePath: string) {
    const fullPath = resolve(KEYPAIRS_DIR, filePath.replace('keypairs/', ''));
    if (!existsSync(fullPath)) {
      throw new Error(
        `Keypair file not found: ${fullPath}\n` +
        `Please run: cd agent-network && ./scripts/generate_keypair.sh`
      );
    }
    const keypairArray = JSON.parse(readFileSync(fullPath, 'utf-8')) as number[];
    const keypairBytes = new Uint8Array(keypairArray);
    return createKeyPairSignerFromBytes(keypairBytes);
  }

  // Load keypairs.json to get all node keypairs
  if (!existsSync(KEYPAIRS_JSON_PATH)) {
    throw new Error(
      `Keypairs JSON not found: ${KEYPAIRS_JSON_PATH}\n` +
      `Please run: cd agent-network && ./scripts/generate_keypair.sh`
    );
  }

  const keypairsJson = JSON.parse(readFileSync(KEYPAIRS_JSON_PATH, 'utf-8')) as KeypairsJson;

  // Load authority and node owner (always single)
  const authority = await loadKeypairFromFile(keypairsJson.authority.keypair_path);
  const nodeOwner = await loadKeypairFromFile(keypairsJson.node_owner.keypair_path);

  // Load all public nodes
  const publicNodes = await Promise.all(
    keypairsJson.public_nodes.map(node => loadKeypairFromFile(node.keypair_path))
  );

  // Load all confidential nodes
  const confidentialNodes = await Promise.all(
    keypairsJson.confidential_nodes.map(node => loadKeypairFromFile(node.keypair_path))
  );

  return {
    authority,
    nodeOwner,
    publicNodes,
    confidentialNodes,
  };
}
