import { createSolanaClient } from 'gill';
import { DacFrontendClient, NodeType, DAC_PROGRAM_ID } from './index.js';
import { deriveNetworkConfigAddress, deriveNodeInfoAddress } from './dacPdas.js';
import { loadTestKeypairs } from '../scripts/load-test-keypairs.js';

/**
 * Test file for DAC SDK functions
 * 
 * Usage:
 *   npm run test:run
 *   or
 *   npx tsx src/test.ts
 * 
 * Note: 
 *   - Run 'npm run generate-keypairs' first to generate test keypairs (authority, node-owner, validator-owner)
 *   - Compute Node and Validator Node keypairs are loaded from agent-network/ (generated by generate_keypair.sh)
 */

// Configuration
const SOLANA_RPC = "localnet";

async function main() {
  console.log('🚀 Starting DAC SDK Tests\n');
  console.log(`RPC URL: ${SOLANA_RPC}`);
  console.log(`Program ID: ${DAC_PROGRAM_ID}\n`);

  // Initialize Solana client
  const solanaClient = createSolanaClient({ urlOrMoniker: SOLANA_RPC });
  const dacClient = new DacFrontendClient(solanaClient);

  // Load test keypairs (generated by scripts/generate-test-keypairs.ts)
  console.log('📝 Loading Test Keypairs...\n');
  const keypairs = await loadTestKeypairs();

  console.log('Loaded Keypairs:');
  console.log(`  Authority:        ${keypairs.authority.address}`);
  console.log(`  Node Owner:       ${keypairs.nodeOwner.address}`);
  console.log(`  Compute Node:     ${keypairs.computeNode.address}`);
  console.log(`  Validator Owner:  ${keypairs.validatorOwner.address}`);
  console.log(`  Validator Node:   ${keypairs.validatorNode.address}\n`);

  // ============================================================================
  // Test 1: Initialize Network
  // ============================================================================
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('Test 1: Initialize Network');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  // Check if network is already initialized
  const existingNetworkConfig = await dacClient.getNetworkConfig();
  
  if (existingNetworkConfig) {
    console.log('✅ Network already initialized!');
    console.log('  Network Config Details:');
    console.log(`    Agent Count: ${existingNetworkConfig.agentCount}`);
    console.log(`    Goal Count: ${existingNetworkConfig.goalCount}`);
    console.log(`    Task Count: ${existingNetworkConfig.taskCount}`);
    console.log(`    Validator Node Count: ${existingNetworkConfig.validatorNodeCount}`);
    console.log(`    Compute Node Count: ${existingNetworkConfig.computeNodeCount}\n`);
    console.log('Skipping initialization...\n');
  } else {
    try {
      const networkConfigCid = 'QmTestNetworkConfig123456789'; // Example IPFS CID
      const allocateGoals = 5n;
      const allocateTasks = 5n;
      const approvedCodeMeasurements = [
        {
          measurement: new Uint8Array(32).fill(1), // Example measurement
          version: { major: 1, minor: 0, patch: 0 },
        },
      ];

      console.log('Network not found. Initializing network...\n');
      console.log('Parameters:');
      console.log(`  Network Config CID: ${networkConfigCid}`);
      console.log(`  Allocate Goals: ${allocateGoals}`);
      console.log(`  Allocate Tasks: ${allocateTasks}`);
      console.log(`  Approved Code Measurements: ${approvedCodeMeasurements.length}\n`);

      const { signature: initSignature, networkConfigAddress } =
        await dacClient.initializeNetwork({
          authority: keypairs.authority,
          cidConfig: networkConfigCid,
          allocateGoals,
          allocateTasks,
          approvedCodeMeasurements,
        });

      console.log('✅ Network initialized successfully!');
      console.log(`  Transaction Signature: ${initSignature}`);
      console.log(`  Network Config Address: ${networkConfigAddress}\n`);

      // Verify network config was created
      const networkConfig = await dacClient.getNetworkConfig();
      if (networkConfig) {
        console.log('✅ Network config fetched:');
        console.log(`  Agent Count: ${networkConfig.agentCount}`);
        console.log(`  Goal Count: ${networkConfig.goalCount}`);
        console.log(`  Task Count: ${networkConfig.taskCount}`);
        console.log(`  Validator Node Count: ${networkConfig.validatorNodeCount}`);
        console.log(`  Compute Node Count: ${networkConfig.computeNodeCount}\n`);
      } else {
        console.log('⚠️  Network config not found (may need to wait for confirmation)\n');
      }
    } catch (error) {
      console.error('❌ Failed to initialize network:');
      console.error(error);
      process.exit(1);
    }
  }

  // ============================================================================
  // Test 2: Register Node
  // ============================================================================
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('Test 2: Register Node');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  try {
    const networkConfigData = await dacClient.getNetworkConfig();
    if (!networkConfigData) {
      throw new Error('Network config not found. Run initializeNetwork first.');
    }

    const networkConfigAddr = await deriveNetworkConfigAddress(DAC_PROGRAM_ID);

    // Test registering a Compute node
    console.log('Checking Compute Node registration...');
    const existingComputeNodeInfo = await dacClient.getNodeInfo(keypairs.computeNode.address);
    
    if (existingComputeNodeInfo) {
      const computeNodeInfoAddress = await deriveNodeInfoAddress(DAC_PROGRAM_ID, keypairs.computeNode.address);
      console.log('✅ Compute Node already registered!');
      console.log(`  Node Info Address: ${computeNodeInfoAddress}`);
      console.log(`  Node Type: ${existingComputeNodeInfo.nodeType}`);
      console.log(`  Status: ${existingComputeNodeInfo.status}\n`);
    } else {
      console.log('Registering Compute Node...');
      const { signature: registerSignature, nodeInfoAddress, nodeTreasuryAddress } =
        await dacClient.registerNode({
          owner: keypairs.nodeOwner,
          networkConfig: networkConfigAddr,
          nodePubkey: keypairs.computeNode.address,
          nodeType: NodeType.Compute,
        });

      console.log('✅ Node registered successfully!');
      console.log(`  Transaction Signature: ${registerSignature}`);
      console.log(`  Node Info Address: ${nodeInfoAddress}`);
      console.log(`  Node Treasury Address: ${nodeTreasuryAddress}\n`);
    }

    // Test registering a Validator node
    console.log('Checking Validator Node registration...');
    console.log(`  Validator Node Pubkey: ${keypairs.validatorNode.address}`);
    
    const existingValidatorNodeInfo = await dacClient.getNodeInfo(keypairs.validatorNode.address);
    
    if (existingValidatorNodeInfo) {
      const validatorNodeInfoAddress = await deriveNodeInfoAddress(DAC_PROGRAM_ID, keypairs.validatorNode.address);
      console.log('✅ Validator Node already registered!');
      console.log(`  Node Info Address: ${validatorNodeInfoAddress}`);
      console.log(`  Node Type: ${existingValidatorNodeInfo.nodeType}`);
      console.log(`  Status: ${existingValidatorNodeInfo.status}\n`);
    } else {
      console.log('Registering Validator Node...');
      const { signature: validatorSignature, nodeInfoAddress: validatorNodeInfoAddress } =
        await dacClient.registerNode({
          owner: keypairs.validatorOwner,
          networkConfig: networkConfigAddr,
          nodePubkey: keypairs.validatorNode.address,
          nodeType: NodeType.Validator,
        });

      console.log('✅ Validator node registered successfully!');
      console.log(`  Transaction Signature: ${validatorSignature}`);
      console.log(`  Node Info Address: ${validatorNodeInfoAddress}\n`);
    }
  } catch (error) {
    console.error('❌ Failed to register node:');
    console.error(error);
    process.exit(1);
  }
}

main().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});
