import { generateExtractableKeyPairSigner, extractBytesFromKeyPairSigner } from 'gill';
import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

/**
 * Generate test keypairs for DAC testing
 * 
 * Generates and saves keypairs for:
 * - Authority (network authority)
 * - Node Owner (owner of compute/validator nodes)
 * - Validator Owner (owner of validator node)
 * 
 * Note: Compute Node and Validator Node keypairs are loaded from
 * agent-network/compute-node-keypair.json and agent-network/validator-node-keypair.json
 * (generated by agent-network/scripts/generate_keypair.sh)
 * 
 * Usage:
 *   npm run generate-keypairs
 *   or
 *   npx tsx scripts/generate-test-keypairs.ts
 */

const KEYPAIRS_DIR = join(process.cwd(), 'test-keypairs');

interface KeypairData {
  address: string;
  keypairBytes: Uint8Array;
}

interface SavedKeypair {
  address: string;
  keypair: number[]; // Solana format: 64-byte array [private_key (32 bytes) + public_key (32 bytes)]
}

async function generateAndSaveKeypair(name: string): Promise<KeypairData> {
  const signer = await generateExtractableKeyPairSigner();
  
  // Extract keypair bytes using gill's utility function
  // This returns 64 bytes: private key (32 bytes) + public key (32 bytes)
  const keypairBytes = await extractBytesFromKeyPairSigner(signer);
  
  const savedKeypair: SavedKeypair = {
    address: signer.address,
    keypair: Array.from(keypairBytes), // Convert to array for JSON
  };
  
  // Save as JSON (Solana format - can be loaded by Rust nodes)
  const jsonPath = join(KEYPAIRS_DIR, `${name}.json`);
  writeFileSync(jsonPath, JSON.stringify(savedKeypair.keypair), 'utf-8');
  
  // Also save a readable format with address
  const readablePath = join(KEYPAIRS_DIR, `${name}.info.json`);
  writeFileSync(readablePath, JSON.stringify(savedKeypair, null, 2), 'utf-8');
  
  return {
    address: signer.address,
    keypairBytes,
  };
}

async function main() {
  console.log('🔑 Generating Test Keypairs for DAC\n');
  
  // Create keypairs directory
  mkdirSync(KEYPAIRS_DIR, { recursive: true });
  
  console.log('Generating keypairs...\n');
  console.log('Note: Compute Node and Validator Node keypairs will be loaded from agent-network/');
  console.log('      (generated by agent-network/scripts/generate_keypair.sh)\n');
  
  // Generate only test keypairs (not node keypairs - those come from agent-network)
  const authority = await generateAndSaveKeypair('authority');
  const nodeOwner = await generateAndSaveKeypair('node-owner');
  const validatorOwner = await generateAndSaveKeypair('validator-owner');
  
  console.log('✅ Test keypairs generated successfully!\n');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('Generated Keypairs:');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  
  console.log(`Authority:        ${authority.address}`);
  console.log(`Node Owner:       ${nodeOwner.address}`);
  console.log(`Validator Owner:  ${validatorOwner.address}\n`);
  console.log('Compute Node and Validator Node keypairs are loaded from agent-network/');
  console.log('See load-test-keypairs.ts for details.\n');
  
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('Saved Files:');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  
  console.log(`Directory: ${KEYPAIRS_DIR}\n`);
  console.log('Files created:');
  console.log('  - authority.json          (Solana format - for Rust nodes)');
  console.log('  - authority.info.json     (Readable format with address)');
  console.log('  - node-owner.json');
  console.log('  - node-owner.info.json');
  console.log('  - validator-owner.json');
  console.log('  - validator-owner.info.json\n');
  console.log('Note: Compute Node and Validator Node keypairs are loaded from:');
  console.log('      - agent-network/compute-node-keypair.json');
  console.log('      - agent-network/validator-node-keypair.json\n');
  
  // Create a summary file with test keypair addresses
  // Note: Node addresses will be loaded from agent-network keypairs
  const summary = {
    authority: authority.address,
    nodeOwner: nodeOwner.address,
    validatorOwner: validatorOwner.address,
    note: 'Compute Node and Validator Node keypairs are loaded from agent-network/ directory. Use loadTestKeypairs() to get all keypairs including nodes.',
  };
  
  const summaryPath = join(KEYPAIRS_DIR, 'keypairs-summary.json');
  writeFileSync(summaryPath, JSON.stringify(summary, null, 2), 'utf-8');
  
  console.log('📄 Summary saved to: keypairs-summary.json\n');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('✅ Done! Keypairs are ready for testing.');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
}

main().catch((error) => {
  console.error('❌ Error generating keypairs:', error);
  process.exit(1);
});



