import { createKeyPairSignerFromBytes } from 'gill';
import { readFileSync, existsSync } from 'fs';
import { join, resolve } from 'path';

/**
 * Load test keypairs from generated files and agent-network keypairs
 * 
 * Loads:
 * - Authority, Node Owner, Validator Owner from test-keypairs/
 * - Compute Node and Validator Node from agent-network/ (generated by generate_keypair.sh)
 * 
 * Usage:
 *   import { loadTestKeypairs } from './scripts/load-test-keypairs.js';
 *   const keypairs = await loadTestKeypairs();
 */

const KEYPAIRS_DIR = join(process.cwd(), 'test-keypairs');
// Path to agent-network directory (assuming clients/sdk is sibling to agent-network)
const AGENT_NETWORK_DIR = resolve(process.cwd(), '../../agent-network');

export interface TestKeypairs {
  authority: Awaited<ReturnType<typeof createKeyPairSignerFromBytes>>;
  nodeOwner: Awaited<ReturnType<typeof createKeyPairSignerFromBytes>>;
  computeNode: Awaited<ReturnType<typeof createKeyPairSignerFromBytes>>;
  validatorOwner: Awaited<ReturnType<typeof createKeyPairSignerFromBytes>>;
  validatorNode: Awaited<ReturnType<typeof createKeyPairSignerFromBytes>>;
}

export async function loadTestKeypairs(): Promise<TestKeypairs> {
  function loadKeypairFromFile(filePath: string) {
    if (!existsSync(filePath)) {
      throw new Error(`Keypair file not found: ${filePath}`);
    }
    const keypairArray = JSON.parse(readFileSync(filePath, 'utf-8')) as number[];
    const keypairBytes = new Uint8Array(keypairArray);
    return createKeyPairSignerFromBytes(keypairBytes);
  }

  function loadTestKeypair(name: string) {
    const jsonPath = join(KEYPAIRS_DIR, `${name}.json`);
    return loadKeypairFromFile(jsonPath);
  }

  // Load test keypairs from test-keypairs directory
  const authority = await loadTestKeypair('authority');
  const nodeOwner = await loadTestKeypair('node-owner');
  const validatorOwner = await loadTestKeypair('validator-owner');

  // Load node keypairs from agent-network directory
  const computeNodePath = join(AGENT_NETWORK_DIR, 'compute-node-keypair.json');
  const validatorNodePath = join(AGENT_NETWORK_DIR, 'validator-node-keypair.json');

  if (!existsSync(computeNodePath)) {
    throw new Error(
      `Compute node keypair not found: ${computeNodePath}\n` +
      `Please run: cd agent-network && ./scripts/generate_keypair.sh`
    );
  }

  if (!existsSync(validatorNodePath)) {
    throw new Error(
      `Validator node keypair not found: ${validatorNodePath}\n` +
      `Please run: cd agent-network && ./scripts/generate_keypair.sh`
    );
  }

  const computeNode = await loadKeypairFromFile(computeNodePath);
  const validatorNode = await loadKeypairFromFile(validatorNodePath);

  return {
    authority,
    nodeOwner,
    computeNode,
    validatorOwner,
    validatorNode,
  };
}
